[project]
name = "autotests-ui"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.55.0",
    "pytest==8.4.2",
    "pytest-playwright==0.7.1",
    "pytest-rerunfailures==16.1",
]
